---

- name: Execute a comand in the remote shell
  hosts: all
  tasks:
     
    - name: Execute a comand in the remote shell
      win_shell: C:\Temp\MyScript.ps1 > C:\Temp\A.txt
      
- name: Pause PRTG Sensor
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: Pause all sensor for host
    uri:
      url: http://192.168.254.155/api/pauseobjectfor.htm?id=2087&duration=30&pausemsg=auto_paused_for_server_maint&username=prtgadmin&password=prtgadmin

- name: Snapshot the server
  hosts: all
  tasks: 

  - name: Create a snapshot
    vmware_guest_snapshot:
      hostname: "192.168.254.148"
      username: "patching@vsphere.local"
      password: "Abc12345*/"
      datacenter: "CFV"
      folder: "CFV/"
      name: "SANDBOX CLONE"
      state: present
      snapshot_name: snap1
      description: snap1_description
      quiesce: no
      memory_dump: no
    delegate_to: localhost
    
   
- name: Install Updates on Server and then reboot
  hosts: all
  tasks: 
  
    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        reboot: yes

- name: Resume PRTG Sensors
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: Resume all sensor for host
    uri:
      url: http://192.168.254.155/api/pause.htm?id=2087&action=1&username=prtgadmin&password=prtgadmin
