---

- name: Execute a comand in the remote shell
  hosts: all
  tasks:
     
    - name: Execute a comand in the remote shell
      win_shell: C:\Temp\MyScript.ps1 > C:\Temp\A.txt
      
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: check out a git repository
    url: https://google.co.cr
