---

- name: Execute a comand in the remote shell
  hosts: all
  tasks:
    
    - name: Pause PRTG
      url: https://google.co.cr
      
    - name: Execute a comand in the remote shell
      win_shell: C:\Temp\MyScript.ps1 > C:\Temp\A.txt
