---

- name: Execute a comand in the remote shell
  hosts: all
  tasks:
     
    - name: Execute a comand in the remote shell
      win_shell: C:\Temp\MyScript.ps1 > C:\Temp\A.txt
      
- name: Call URL from Ansible Host
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: Call Google
    uri:
      url: https://google.co.cr
