---

- name:  Update LINUX Machines
  serial: 1
  hosts: LINUX
  become: true
  tasks:
  
  - name: CreateBodyTemplates
    vars:
     VarVMID: "{{ vCenter_moid }}"
     VarHostName: "{{ hostnameIP }}"
     VarReboot: "{{ AutoReboot }}"
     VarLink: "{{ MailLink }}"
    script: /BodyTemplates/EmailScript.sh "{{ VarVMID }}" '"{{ VarHostName }}"' "{{ VarReboot }}" "{{ VarLink }}"
    delegate_to: localhost
  
  - name: Send Start Notification
    vars:
      MailOptionHostName: "{{ hostnameIP }}"
      MailOptionHost: "{{ MailServer }}"
      MailOptionPort: "{{ MailPort }}"
      MailOptionUser: "{{ MailUser }}"
      MailOptionPass: "{{ MailPassword }}"
      MailOptionTo1: "{{ MailTo }}"
      MailOptionTo2: "{{ MailTo2 }}"
      MailOptionCC: "{{ MailCC }}"
      MailOptionSubject: "{{ MailSubject }}"
      VarVMID: "{{ vCenter_moid }}"
    mail:
      host: "{{ MailOptionHost }}"
      port: "{{ MailOptionPort }}"
      from: "{{ MailOptionUser }}"
      username: "{{ MailOptionUser }}"
      password: "{{ MailOptionPass }}"
      to:
      - "{{ MailOptionTo1 }}"
      - "{{ MailOptionTo2 }}"
      cc: "{{ MailOptionCC }}"
      subject: "{{ MailOptionSubject }}"
      subtype: html
      body: "{{ lookup('file', '/tmp/{{ VarVMID }}_Start.html') }}"
    delegate_to: 127.0.0.1
  
  - name: Create a Snapshot
    vars:
     vOptionvCenter: "{{ vCenter_hostname }}"
     vOptionusername: "{{ vCenter_username }}"
     vOptionpassword: "{{ vCenter_Password }}"
     vOptionDC: "{{ vCenter_datacenter }}"
     vOptionMachineID: "{{ vCenter_moid }}"
     vOptionState: "{{ vCenter_state }}"
     vOptionSnapName: "{{ vCenter_snapshot_name }}"
     vOptionSnapDescription: "{{ vCenter_description }}"
     vOptionQuiesce: "{{ vCenter_quiesce }}"
     vOptionMemorySnap: "{{ vCenter_memory_dump }}"
     vOptionIsVirtual: "{{ Virtual }}"
    vmware_guest_snapshot:
      hostname: "{{ vOptionvCenter }}"
      username: "{{ vOptionusername }}"
      password: "{{ vOptionpassword }}"
      datacenter: "{{ vOptionDC }}"
      moid: "{{ vOptionMachineID }}"
      state: "{{ vOptionState }}"
      snapshot_name: "{{ vOptionSnapName }}"
      description: "{{ vOptionSnapDescription }}"
      quiesce: "{{ vCenter_quiesce }}"
      memory_dump: "{{ vCenter_memory_dump }}"
      validate_certs: no
    delegate_to: localhost
    when: vOptionIsVirtual|bool
  
  - name: .rpm upgrade server
    yum: >
      update_cache=yes
      name=*
      state=latest
      update_cache=yes
    when: >
      ansible_distribution == 'CentOS'
      or
      ansible_distribution == 'RedHat'
        
  - name: .deb do dist-upgrade
    apt: >
      update_cache=yes
      cache_valid_time=1200
      upgrade=dist
    when: >
      ansible_distribution == 'Debian'
      or
      ansible_distribution == 'Ubuntu'
        
  - name: Reboot a slow machine that might have lots of updates to apply
    reboot:
      reboot_timeout: 3600  
  
  - name: Send Finish Notification
    vars:
      MailOptionHostName: "{{ hostnameIP }}"
      MailOptionHost: "{{ MailServer }}"
      MailOptionPort: "{{ MailPort }}"
      MailOptionUser: "{{ MailUser }}"
      MailOptionPass: "{{ MailPassword }}"
      MailOptionTo1: "{{ MailTo }}"
      MailOptionTo2: "{{ MailTo2 }}"
      MailOptionCC: "{{ MailCC }}"
      MailOptionSubject: "{{ MailSubject }}"
      VarVMID: "{{ vCenter_moid }}"
    mail:
      host: "{{ MailOptionHost }}"
      port: "{{ MailOptionPort }}"
      from: "{{ MailOptionUser }}"
      username: "{{ MailOptionUser }}"
      password: "{{ MailOptionPass }}"
      to:
      - "{{ MailOptionTo1 }}"
      - "{{ MailOptionTo2 }}"
      cc: "{{ MailOptionCC }}"
      subject: "{{ MailOptionSubject }}"
      subtype: html
      body: "{{ lookup('file', '/tmp/{{ VarVMID }}_End.html') }}"
    delegate_to: 127.0.0.1

- name: Update Windows Machines
  hosts: WINDOWS
  serial: 1
  tasks:
  
  - name: CreateBodyTemplates
    vars:
     VarVMID: "{{ vCenter_moid }}"
     VarHostName: "{{ hostnameIP }}"
     VarReboot: "{{ AutoReboot }}"
     VarLink: "{{ MailLink }}"
    script: /BodyTemplates/EmailScript.sh "{{ VarVMID }}" '"{{ VarHostName }}"' "{{ VarReboot }}" "{{ VarLink }}"
    delegate_to: localhost
  
  - name: Send Start Notification
    vars:
      MailOptionHostName: "{{ hostnameIP }}"
      MailOptionHost: "{{ MailServer }}"
      MailOptionPort: "{{ MailPort }}"
      MailOptionUser: "{{ MailUser }}"
      MailOptionPass: "{{ MailPassword }}"
      MailOptionTo1: "{{ MailTo }}"
      MailOptionTo2: "{{ MailTo2 }}"
      MailOptionCC: "{{ MailCC }}"
      MailOptionSubject: "{{ MailSubject }}"
      MailOptionBody: "{{ MailBody }}"
      VarVMID: "{{ vCenter_moid }}"
    mail:
      host: "{{ MailOptionHost }}"
      port: "{{ MailOptionPort }}"
      from: "{{ MailOptionUser }}"
      username: "{{ MailOptionUser }}"
      password: "{{ MailOptionPass }}"
      to:
      - "{{ MailOptionTo1 }}"
      - "{{ MailOptionTo2 }}"
      cc: "{{ MailOptionCC }}"
      subject: "{{ MailOptionSubject }}"
      subtype: html
      body: "{{ lookup('file', '/tmp/{{ VarVMID }}_Start.html') }}"
    delegate_to: 127.0.0.1
  
  - name: Create a Snapshot
    vars:
     vOptionvCenter: "{{ vCenter_hostname }}"
     vOptionusername: "{{ vCenter_username }}"
     vOptionpassword: "{{ vCenter_Password }}"
     vOptionDC: "{{ vCenter_datacenter }}"
     vOptionMachineID: "{{ vCenter_moid }}"
     vOptionState: "{{ vCenter_state }}"
     vOptionSnapName: "{{ vCenter_snapshot_name }}"
     vOptionSnapDescription: "{{ vCenter_description }}"
     vOptionQuiesce: "{{ vCenter_quiesce }}"
     vOptionMemorySnap: "{{ vCenter_memory_dump }}"
     vOptionIsVirtual: "{{ Virtual }}"
    vmware_guest_snapshot:
      hostname: "{{ vOptionvCenter }}"
      username: "{{ vOptionusername }}"
      password: "{{ vOptionpassword }}"
      datacenter: "{{ vOptionDC }}"
      moid: "{{ vOptionMachineID }}"
      state: "{{ vOptionState }}"
      snapshot_name: "{{ vOptionSnapName }}"
      description: "{{ vOptionSnapDescription }}"
      quiesce: "{{ vCenter_quiesce }}"
      memory_dump: "{{ vCenter_memory_dump }}"
      validate_certs: no
    delegate_to: localhost
    when: vOptionIsVirtual|bool
    
    
  - name: Remove Old Log File
    vars:
     VarLoc: "{{ LogLocation }}"
     VarLog: "{{ LogFile }}"
    win_shell: Remove-Item {{ VarLoc }}{{ VarLog }} -ErrorAction Ignore
    ignore_errors: yes
    
  - name: Install Windows Updates on Server and then reboot
    vars:
     VarLoc: "{{ LogLocation }}"
     VarLog: "{{ LogFile }}"
     VarReboot: "{{ AutoReboot }}"
    win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      reboot: "{{ VarReboot }}"
      reboot_timeout: 7200
      log_path: "{{ VarLoc }}{{ VarLog }}"
        
  - name: Fetch Log File
    vars:
     VarLoc: "{{ LogLocation }}"
     VarLog: "{{ LogFile }}"
    fetch: src="{{ VarLoc }}{{ VarLog }}" dest=/{{ VarLog }} flat=yes
  
  - name: Send Finish Notification
    vars:
      MailOptionHostName: "{{ hostnameIP }}"
      MailOptionHost: "{{ MailServer }}"
      MailOptionPort: "{{ MailPort }}"
      MailOptionUser: "{{ MailUser }}"
      MailOptionPass: "{{ MailPassword }}"
      MailOptionTo1: "{{ MailTo }}"
      MailOptionTo2: "{{ MailTo2 }}"
      MailOptionCC: "{{ MailCC }}"
      MailOptionSubject: "{{ MailSubject }}"
      MailOptionBody: "{{ MailBody }}"
      VarVMID: "{{ vCenter_moid }}"
      VarLog: "{{ LogFile }}"
    mail:
      host: "{{ MailOptionHost }}"
      port: "{{ MailOptionPort }}"
      from: "{{ MailOptionUser }}"
      username: "{{ MailOptionUser }}"
      password: "{{ MailOptionPass }}"
      to:
      - "{{ MailOptionTo1 }}"
      - "{{ MailOptionTo2 }}"
      cc: "{{ MailOptionCC }}"
      subject: "{{ MailOptionSubject }}"
      subtype: html
      body: "{{ lookup('file', '/tmp/{{ VarVMID }}_End.html') }}"
      attach:
      - /{{ VarLog }}
    delegate_to: 127.0.0.1
