---
    
- name: Send Finish Notification
  hosts: all
  connection: local
  tasks:
  
  - name: Sending Email
    vars:
      MailOptionHostName: "{{ hostnameIP }}"
      MailOptionHost: "{{ MailServer }}"
      MailOptionPort: "{{ MailPort }}"
      MailOptionUser: "{{ MailUser }}"
      MailOptionPass: "{{ MailPassword }}"
      MailOptionTo: "{{ MailTo }}"
      MailOptionSubject: "{{ MailSubject }}"
      MailOptionBody: "{{ MailBody }}"
    mail:
      host: "{{ MailOptionHost }}"
      port: "{{ MailOptionPort }}"
      username: "{{ MailOptionUser }}"
      password: "{{ MailOptionPass }}"
      to: "{{ MailOptionTo }}"
      subject: STARTED "{{ MailOptionHostName }}"
      body: STARTED "{{ MailOptionHostName }}"
    delegate_to: 127.0.0.1
      
- name: Snapshot VM
  hosts: all
  tasks: 
  
  - name: Create a Snapshot
    vmware_guest_snapshot:
      hostname: "192.168.254.148"
      username: "patching@vsphere.local"
      password: "Abc12345*/"
      datacenter: "CFV"
      moid: vm-65
      state: present
      snapshot_name: Patching
      description: Before patching snap
      quiesce: no
      memory_dump: no
      validate_certs: no
    delegate_to: localhost
    
    
- name: Install Updates on Server and then reboot
  hosts: all
  tasks: 
    - name: Install all security, critical, and rollup updates
      win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        reboot: yes
        reboot_timeout: 7200
        
- name: Send Finish Notification
  hosts: all
  connection: local
  tasks:
  
  - name: Sending Email
    vars:
      MailOptionHostName: "{{ hostnameIP }}"
      MailOptionHost: "{{ MailServer }}"
      MailOptionPort: "{{ MailPort }}"
      MailOptionUser: "{{ MailUser }}"
      MailOptionPass: "{{ MailPassword }}"
      MailOptionTo: "{{ MailTo }}"
      MailOptionSubject: "{{ MailSubject }}"
      MailOptionBody: "{{ MailBody }}"
    mail:
      host: "{{ MailOptionHost }}"
      port: "{{ MailOptionPort }}"
      username: "{{ MailOptionUser }}"
      password: "{{ MailOptionPass }}"
      to: "{{ MailOptionTo }}"
      subject: ENDED "{{ MailOptionHostName }}"
      body: ENDED "{{ MailOptionHostName }}"
    delegate_to: 127.0.0.1
