---
    
- name: Start Notification Email
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: Sending an e-mail using Gmail SMTP servers
    mail:
      host: smtp.gmail.com
      port: 587
      username: ansibletesting2020@gmail.com
      password: szmvgvbdbkwetezk
      to: cfernandez@t4.cr
      subject: Ansible-report
      body: System {{ job.name }} Started.
    delegate_to: localhost
      
- name: Snapshot the server
  hosts: all
  tasks: 
  
  - name: Create a snapshot
    vmware_guest_snapshot:
      hostname: "192.168.254.148"
      username: "patching@vsphere.local"
      password: "Abc12345*/"
      datacenter: "CFV"
      moid: vm-65
      state: present
      snapshot_name: Patching
      description: Before patching snap
      quiesce: no
      memory_dump: no
      validate_certs: no
    delegate_to: localhost
    
    
- name: Install Updates on Server and then reboot
  hosts: all
  tasks: 
    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        reboot: yes
        reboot_timeout: 7200
        
- name: Start Notification Email
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: Sending an e-mail using Gmail SMTP servers
    mail:
      host: smtp.gmail.com
      port: 587
      username: ansibletesting2020@gmail.com
      password: szmvgvbdbkwetezk
      to: cfernandez@t4.cr
      subject: Ansible-report
      body: System {{ job.name }} Finished.
    delegate_to: localhost
