---

- name: Check Windows For Updates
  hosts: WINDOWS
  tasks:

  - name: Remove Old Log File
    vars:
     VarLoc: "{{ LogLocation }}"
     VarLog: "{{ LogFile }}"
    win_shell: Remove-Item {{ VarLoc }}{{ VarLog }} -ErrorAction Ignore
    ignore_errors: yes
    
  - name: Check for Updates
    vars:
     VarLoc: "{{ LogLocation }}"
     VarLog: "{{ LogFile }}"
    win_updates:
      category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      state: searched
      log_path: "{{ VarLoc }}{{ VarLog }}"
      
- name: Create BodyTemplate and Log Folder
  hosts: localhost
  become: true
  tasks:
  
  - name: CreateBodyTemplate
    vars:
     VarJobID: "{{ tower_job_id }}"
     VarLink: "{{ MailLink }}"
    script: /BodyTemplates/EmailScript2.sh "{{ VarJobID }}" "{{ VarLink }}"
    delegate_to: localhost

  - name: Create LogFolder
    shell:
     cmd: mkdir /tmp/{{ tower_job_id }}/
        
- name: Fetch Logs
  hosts: WINDOWS
  tasks:
  
  - name: Fetch Log File
    vars:
     VarLoc: "{{ LogLocation }}"
     VarLog: "{{ LogFile }}"
    fetch: src="{{ VarLoc }}{{ VarLog }}" dest=/tmp/{{ tower_job_id }}/{{ VarLog }} flat=yes
   
- name: Send Email Report
  hosts: localhost
  become: true
  tasks:
  
  - name: Consolidate Log Files
    vars:
     VarJobID: "{{ tower_job_id }}"
    script: /BodyTemplates/UpdatesReport.sh "{{ VarJobID }}"
    delegate_to: localhost
 
  - name: Send Finish Notification
    vars:
      MailOptionHostName: "{{ hostnameIP }}"
      MailOptionHost: "{{ MailServer }}"
      MailOptionPort: "{{ MailPort }}"
      MailOptionUser: "{{ MailUser }}"
      MailOptionPass: "{{ MailPassword }}"
      MailOptionTo1: "{{ MailTo }}"
      MailOptionTo2: "{{ MailTo2 }}"
      MailOptionCC: "{{ MailCC }}"
      MailOptionSubject: "{{ MailSubject }}"
      VarLog: "{{ LogFile }}"
    mail:
      host: "{{ MailOptionHost }}"
      port: "{{ MailOptionPort }}"
      from: "{{ MailOptionUser }}"
      username: "{{ MailOptionUser }}"
      password: "{{ MailOptionPass }}"
      to:
      - "{{ MailOptionTo1 }}"
      - "{{ MailOptionTo2 }}"
      cc: "{{ MailOptionCC }}"
      subject: "{{ MailOptionSubject }}"
      subtype: html
      body: "{{ lookup('file', '/tmp/{{ tower_job_id }}.html') }}"
      attach:
      - /tmp/{{ tower_job_id }}/{{ tower_job_id }}.log
    delegate_to: 127.0.0.1
